apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-docker
  name: hello-docker
  namespace: foo
spec:
  containers:
   - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
